# OpenAI Demo Configuration
provider:
  name: "openai"
  api_key: "${OPENAI_API_KEY}"
  base_url: null

model_settings:
  name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000
  stream: true

context:
  system_message: |
    You are a helpful AI assistant with access to tools.
    Be concise and friendly in your responses.

tools:
  enabled: true
  packs: ["common"]
  timeout: 30

memory:
  enabled: true
  max_turns: 10
  store_path: "./memory/openai_demo"

logging:
  level: "INFO"
