# Azure OpenAI Integration Example
#
# This configuration demonstrates how to use Azure OpenAI with yamllm-core.
# Replace placeholder values with your actual Azure OpenAI credentials.

provider:
  name: "azure_openai"
  model: "gpt-4"  # Your deployed model name in Azure OpenAI
  api_key: ${AZURE_OPENAI_API_KEY}  # Use environment variable for API key
  base_url: ${AZURE_OPENAI_ENDPOINT}  # Azure OpenAI endpoint
  extra_settings:
    api_version: "2023-05-15"  # Azure OpenAI API version
    embedding_deployment: "text-embedding-ada-002"  # Optional: specify embedding model

model_settings:
  temperature: 0.7
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop_sequences: []

request:
  timeout: 30
  retry:
    max_attempts: 3
    initial_delay: 1
    backoff_factor: 2

context:
  system_prompt: "You are a helpful assistant powered by Azure OpenAI."
  max_context_length: 4096
  memory:
    enabled: false
    max_messages: 10
    session_id: null
    conversation_db: null
    vector_store:
      index_path: null
      metadata_path: null
      top_k: null

output:
  format: "text"
  stream: true

logging:
  level: "INFO"
  file: "yamllm.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

safety:
  content_filtering: true
  max_requests_per_minute: 60
  sensitive_keywords: []

tools:
  enabled: true
  tool_timeout: 30
  tool_list: ["web_search", "calculator", "weather"]