remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: YAMLLM
description: YAML-based LLM configuration and execution
show_downloads: true
google_analytics:
theme: cayman

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/