theme: jekyll-theme-cayman
plugins:
  - jekyll-theme-cayman
  - jekyll-seo-tag

title: YAMLLM
description: YAML-based LLM configuration and execution
show_downloads: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/